[package]
name = "ddbug"
version = "0.1.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]

[dependencies]
env_logger = "0.3.5"
gimli = { path = "../gimli" }
log = "0.3.6"
memmap = "0.4.0"
xmas-elf = "0.3"
