[package]
name = "ddbug"
version = "0.2.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Display debugging information"
repository = "https://github.com/philipc/ddbug"
readme = "README.md"
keywords = ["debug", "DWARF", "PDB"]
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"

[dependencies]
clap = "2.26"
env_logger = "0.5"
fnv = "1.0"
log = "0.4"
marksman_escape = "0.1"
memmap = "0.6"
panopticon-core = { git = "https://github.com/das-labor/panopticon", rev = "33ffec0d6d379d51b38d6ea00d040f54b1356ae4" }
panopticon-amd64 = { git = "https://github.com/das-labor/panopticon", rev = "33ffec0d6d379d51b38d6ea00d040f54b1356ae4" }
typed-arena = "1.3"
ddbug_parser = { path = "../parser" }

[features]
system_alloc = []
default = []
